### ISSUE TITLE
I'm getting image not found locally

### ISSUE THREAD

**Issue by abirstolov** [Microsoft/dotnet-framework-docker-samples#11]
ran the 'docker build -t app-app .' command
no errors:

> PS E:\Development\docker\dotnet-framework-docker-samples\dotnetapp-4.6.2> docker build -t my-app .
> Sending build context to Docker daemon   214 kB
> Step 1/4 : FROM microsoft/dotnet-framework:4.6.2
> 4.6.2: Pulling from microsoft/dotnet-framework
> 3889bb8d808b: Pulling fs layer
> 423d66441981: Downloading
> unknown blob

then docker run my-app returns
> Unable to find image 'my-app:latest' locally

**Comment by MichaelSimons** [comment]
@abirstolov, I suspect you are running Docker for Windows in `Linux mode`.  The full .NET Framework is only supported on Windows therefore the corresponding Docker images can only be run in `Windows mode`.  See https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers for details on switching between the two modes.  If you want to run .NET on Linux, then you would need to be using [.NET Core](https://www.microsoft.com/net/download/core) and the corresponding [Docker images](https://hub.docker.com/r/microsoft/dotnet/).

**Comment by rakeshsinghranchi** [comment]
@abirstolov , Please let me know if above suggestion from @MichaelSimons worked for you.
