### ISSUE TITLE
Github Url for dotnetapp-4.7 sample is Incorrect

### ISSUE THREAD

**Issue by bahreex** [Microsoft/dotnet-framework-docker-samples#21]
The URI given in Readme.md for the dotnetapp-4.7 is Incorrect

>Git clone this repository or otherwise copy this sample to your machine: git clone
> https://github.com/dotnet/dotnet-framework-docker-samples/dotnetapp-4.7

**Comment by MichaelSimons** [comment]
This issue has been addressed with Microsoft/dotnet-framework-docker#126
