### ISSUE TITLE
getting the error dotnet is not recognized

### ISSUE THREAD

**Issue by almahesh** [Microsoft/dotnet-framework-docker-samples#25]
Getting the following error when i do >docker build -t my-dotnet462-app .

Sending build context to Docker daemon  873.5kB
Step 1/8 : FROM microsoft/dotnet-framework:4.6.2
 ---> 6a26127feff4
Step 2/8 : WORKDIR /app
 ---> Using cache
 ---> e670ba63085d
Step 3/8 : COPY *.csproj ./
 ---> Using cache
 ---> 9172c87fac16
Step 4/8 : RUN dotnet restore
 ---> Running in c8f7abfff5c1
'dotnet' is not recognized as an internal or external command,
operable program or batch file.
The command 'cmd /S /C dotnet restore' returned a non-zero code: 1

'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by MichaelSimons** [comment]
@almahesh  - It looks like you are using a `microsoft/dotnet-framework` image to perform a build.  These images on contain the .NET Framework runtime.  You should be using the `microsoft/dotnet-framework-build` images for building.

`FROM microsoft/dotnet-framework-build:4.7.1`

**Comment by MichaelSimons** [comment]
Closing.  If the guidance I gave doesn't resolve the situation feel free to respond.
